name: Docker Base Image CI

on:
  push:
    paths-ignore: 
      - "README.md"
    branches:
    - master
  schedule:
    - cron:  "0 0 * * 0"
  pull_request:
    paths-ignore: 
      - "README.md"
    branches:
    - master


jobs:
  
  build:
    name: Docker Image ${{ matrix.image }} ${{ matrix.tag }} CI
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - tag: ""

    steps:
      - uses: actions/checkout@v1
        
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
        
      - name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}    
      
      - name: Docker Image Build
        uses: docker/build-push-action@v2
        with:
            push: true
            tags: thost96/nextcloud:${{ matrix.tag }}      
            build-args: |
              TAG=${{matrix.version}}
              LOCALES_VERSION=${{matrix.locales}}
              TZDATA_VERSION=${{matrix.tzdata}}
